version: "3"
services:
  labfile-mail:
    image: maildev/maildev
    container_name: labfile-mail
    ports:
      - "1080:1080"
#    labfile-db:
#      image: mysql:5.7.22
#      container_name: labfile-db
#      ports:
#          - "3306:3306"
#      environment:
#          MYSQL_DATABASE: labfile_db
#          MYSQL_ROOT_PASSWORD: password
#      volumes:
#          - dbdata:/var/lib/mysql
#
#volumes:
#      dbdata:
#          driver: local
