# Generated by Django 4.2.2 on 2023-06-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
