# Generated by Django 4.2.2 on 2023-06-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
