# Generated by Django 4.2.1 on 2023-06-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='image',
            field=models.FileField(null=True, upload_to='phots'),
        ),
        migrations.DeleteModel(
            name='Privilege',
        ),
    ]
