# Generated by Django 4.2.2 on 2023-06-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labfile', '0002_utilisateur_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='nom',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('PERSONNEL', 'personnel'), ('STAGIAIRE', 'stagiaire')], max_length=15),
        ),
    ]
