# Generated by Django 4.2.2 on 2023-06-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labfile', '0002_alter_document_emplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='phots'),
        ),
    ]
