# Generated by Django 4.2.1 on 2023-06-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labfile', '0002_alter_utilisateur_image_delete_privilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='categorie',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
