# Generated by Django 4.2.2 on 2023-06-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labfile', '0003_alter_role_nom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'permissions': [('can_view_site', 'can view tha private site')]},
        ),
    ]
