# Generated by Django 4.2.2 on 2023-06-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labfile', '0005_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'permissions': [('can_view_site', 'can view the private site'), ('can_view_dashboard', 'can view the dashboard')]},
        ),
    ]
